import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"

import { CartProvider } from "./context/cartContext";
import { Toaster } from "sonner";
import Providers from "./provider";
import { AppChrome } from "./AppChrome";
import ProtectedRoute from "./Components/ProtectedRoute";
import OfflineGuard from "./Components/OfflineGuard";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Ecommerce Web App",
    description: "Generated by create next app",
};



export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            style={{ backgroundColor: "white" }}
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="flex flex-col flex-1 min-h-screen">
                <OfflineGuard>

                    <Providers>
                        <CartProvider>


                            <AppChrome>{children}</AppChrome>
                        </CartProvider>
                    </Providers>
                </OfflineGuard>
                <Toaster position="bottom-right" />
            </body>
        </html>
    );
}
